before_install:
  - "pip install --upgrade --upgrade-strategy=eager pip wheel pytest requests setuptools"
language: python
cache:
  - apt
  - pip
dist: xenial
sudo: false
python:
  - "3.6"
  - "3.7"
  - "3.8"
matrix:
  include:
    - python: "3.8"
      env: NMODE=flake8
env:
    NMODE=nikola
install:
  - "if [[ $NMODE == 'nikola' ]]; then pip install git+https://github.com/getnikola/nikola.git#egg=Nikola; fi"
  # test dependencies
  - "if [[ $NMODE == 'nikola' ]]; then pip install pybtex; fi"
  - "if [[ $NMODE == 'flake8' ]]; then pip install flake8; fi"
script:
  - "if [[ $NMODE == 'nikola' ]]; then py.test tests/; fi"
  - "if [[ $NMODE == 'flake8' ]]; then flake8 v*/; fi"
notifications:
  irc:
    channels:
      - "chat.freenode.net#nikola"
    template:
      - "[PLUGINS] %{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "[PLUGINS] Change view: %{compare_url}"
      - "[PLUGINS] Build details: %{build_url}"
    skip_join: false
    use_notice: true
